Repository intelowlproject/IntelOwl, pull requests merged in 2021-07, with the labels that each got.

#526 [Fix] add missing secrets to new analyzer config
  configuration/analyzer_config.json
  configuration/convert_config.py
Labels: bug

#551 Fixes #390: Split `send_analysis_request` into `analyze_file` and `analyze_observable`
  api_app/analyzers_manager/controller.py
  api_app/api.py
  api_app/helpers.py
  api_app/serializers.py
  api_app/urls.py
  tests/test_api.py
Labels: GSoC-2021

#556 Fixes #543: Removed CirclePDNS env variable default value
  docker/env_file_app_template
Labels: GSoC-2021, bug

#557 Fixes #555: Moved download_sample to JobViewSet action
  api_app/api.py
  api_app/urls.py
  tests/test_api.py
Labels: GSoC-2021

#580 [release] v2.5.0
  .github/CHANGELOG.md
  .github/dependabot.yml
  README.md
  api_app/script_analyzers/file_analyzers/cuckoo_scan.py
  api_app/script_analyzers/file_analyzers/file_info.py
  api_app/script_analyzers/observable_analyzers/abuseipdb.py
  api_app/script_analyzers/observable_analyzers/dehashed.py
  api_app/script_analyzers/observable_analyzers/otx.py
  api_app/script_analyzers/repo_downloader.sh
  configuration/analyzer_config.json
  docker/.env
  docker/entrypoint_uwsgi.sh
  docker/env_file_app_ci
  docker/env_file_app_template
  docker/scripts/manage.sh
  docs/source/Advanced-Usage.md
  docs/source/Usage.md
  docs/source/conf.py
  docs/source/schema.yml
  integrations/apk_analyzers/requirements.txt
  integrations/box-js/Dockerfile
  integrations/box-js/requirements.txt
  integrations/qiling/requirements.txt
  integrations/static_analyzers/Dockerfile
  integrations/static_analyzers/requirements.txt
  integrations/thug/requirements.txt
  requirements.txt
  start.py
  test-requirements.txt
  tests/test_observables.py
  tests/utils.py
Labels: PR: release
